### PR TITLE
fix: upon finding a bitcoin attributes deposited tx, ensure that we have it and all of its ancestors

### LINKED ISSUE #79: Upon a bitcoin reorg that includes a block in a Bitcoin Attributes Deposited Transaction, a node cannot sync
### Reproduction steps:
* given a Hemi chain that has a Bitcoin Attributes Deposited Transaction on it, re-org that block off of the bitcoin chain
  * I do this via `invalidateblock`
* sync a new node
  * I use snap sync

### Issue:

The node that is syncing cannot find the invalid bitcoin block, and thus cannot sync.

It _should_ get this from another peer in the network, but it does not.

You'll see something like this:
```shell
op-geth-l2-non-sequencing-snap-sync-1  | WARN [04-24|15:06:17.755] Header 24019d58e523ad49079f9a7ac6e7ab87817d2ae8d4bf27513280d7b1475bc64b not found err="db block header by hash: block header not found: 24019d58e523ad49079f9a7ac6e7ab87817d2ae8d4bf27513280d7b1475bc64b"
op-geth-l2-non-sequencing-snap-sync-1  | WARN [04-24|15:06:17.940] Header 24019d58e523ad49079f9a7ac6e7ab87817d2ae8d4bf27513280d7b1475bc64b not found err="db block header by hash: block header not found: 24019d58e523ad49079f9a7ac6e7ab87817d2ae8d4bf27513280d7b1475bc64b"
op-geth-l2-non-sequencing-snap-sync-1  | WARN [04-24|15:06:52.941] Header 24019d58e523ad49079f9a7ac6e7ab87817d2ae8d4bf27513280d7b1475bc64b not found err="db block header by hash: block header not found: 24019d58e523ad49079f9a7ac6e7ab87817d2ae8d4bf27513280d7b1475bc64b"
```

### Workaround:

on the syncing node, you can `debug.setHead` to a block before the one with the missing bitcoin block, and it recovers.

### PR DESCRIPTION
**Pull request by ClaytonNorthey92**
* when forkChoiceUpdated is called, check the payload attributes for bitcoin attributes deposited transactions
* ensure that we have the headers and canonical tip stored in the aforementioned bitcoin attributes deposited transaction, otherwise request it from peers
* upon receiving a bitcoin block from peers via p2p, ensure that we have all ancestors

fixes https://github.com/hemilabs/op-geth/issues/79

### CODE REVIEW

**Review by jcvernaleo — APPROVED** [review]
OK

File: eth/catalyst/api.go [hunk 1]
```diff
@@ -475,6 +475,17 @@ func (api *ConsensusAPI) forkchoiceUpdated(update engine.ForkchoiceStateV1, payl
...
 			transactions = append(transactions, &tx)
+
+			if tx.Type() == types.BtcAttributesDepositedTxType {
+				var btcDepData types.BtcAttributesDepositData
+				if err := btcDepData.UnmarshalBinary(tx.Data()); err != nil {
+					return engine.STATUS_INVALID, engine.InvalidForkChoiceState.With(errors.New("invalid BtcAttributesDepositData"))
+				} else {
+					canonicalTip := common.Hash(btcDepData.CanonicalTip)
+					log.Trace("Requesting Bitcoin block from peers", "hash", canonicalTip)
+					api.eth.RequestBitcoinBlocksFromPeers(canonicalTip)
```
Comment (ClaytonNorthey92) [inline eth/catalyst/api.go]: tx that adds non-canonical headers to the chain knowledge but doesn't change the canonical tip, request and make sure we have them before we process the l2 block.

ensure that canonical tip - 2 and all ancestors are available before processing l2 block

Comment (ClaytonNorthey92) [reply eth/catalyst/api.go]: permanent block rejection vs. block may be valid later

Comment (ClaytonNorthey92) [reply eth/catalyst/api.go]: use last header in btc attr deposited transaction, instead of canonical tip

File: eth/backend.go [hunk 2]
```diff
@@ -515,6 +516,35 @@ func New(stack *node.Node, config *ethconfig.Config, ctx context.Context) (*Ethe
...
+		log.Trace("BTC block already in TBC, skipping peer request", "hash", hash)
+		return true
+	}
+
+	
+	go func() {
+		log.Trace("BTC block not found in TBC, making peer requests for block", "hash", hash)
+
+		for _, peer := range e.handler.peers.all() {
+			if err := peer.RequestBtcBlocks([]common.Hash{hash}); err != nil {
```
Comment (AL-CT) [inline eth/backend.go]: Might be worth it to pass all hashes (or at least groups of them) to this method, so that we can make a single `RequestBtcBlocks` request with all the blocks we are missing to each peer, rather than splitting them up.

**Review by AL-CT — APPROVED** [review]
Just a suggestion for you to consider, otherwise LGTM 👍

File: eth/backend.go (hunk 2 above)
Comment (ClaytonNorthey92) [reply eth/backend.go]: good idea. I am not 100% sure of the upper-limit to how large the number of hashes could be.  I imagine that it's not many, but to be sure I will batch the requests, I'll do a safe limit of 5 to start.

Comment (ClaytonNorthey92) [reply eth/backend.go]: hey @AL-CT after some thought, I would prefer to leave this as is.  two main reasons:
1. readability.  batching these would require maintaining a slice or array to send, which would add a bit more code and would hurt readability
2. keeping the requests small and fast.  batching multiple of these will lead to more data being sent per message. I imagine that is slower, however probably not noticeable to a human, but _may_ put us at risk of timeouts.
